BitBag\SyliusCmsPlugin\Entity\InfoArticle:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [code]
              message: 'bitbag_sylius_cms_plugin.info_article.code.unique'
              groups: ['bitbag']
    properties:
        code:
            - NotBlank:
                  message: 'bitbag_sylius_cms_plugin.info_article.code.not_blank'
                  groups: ['bitbag']
            - Length:
                  min: 2
                  max: 250
                  minMessage: 'bitbag_sylius_cms_plugin.info_article.code.min_length'
                  maxMessage: 'bitbag_sylius_cms_plugin.info_article.code.max_length'
                  groups: ['bitbag']
        translations:
            - Valid: ~
