BitBag\SyliusCmsPlugin\Entity\MapPointTranslation:
    properties:
        name:
            - NotBlank:
                  message: bitbag_sylius_cms_plugin.map_point.name.not_blank
                  groups: [bitbag]
            - Length:
                  min: 2
                  max: 250
                  minMessage: bitbag_sylius_cms_plugin.map_point.name.min_length
                  maxMessage: bitbag_sylius_cms_plugin.map_point.name.max_length
                  groups: [bitbag]
