sylius_resource:
    resources:
        bitbag_sylius_cms_plugin.info_article:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusCmsPlugin\Entity\InfoArticle
                interface: BitBag\SyliusCmsPlugin\Entity\InfoArticleInterface
                form: BitBag\SyliusCmsPlugin\Form\Type\InfoArticleType
                repository: BitBag\SyliusCmsPlugin\Repository\InfoArticleRepository
            translation:
                classes:
                    model: BitBag\SyliusCmsPlugin\Entity\InfoArticleTranslation
                    interface: BitBag\SyliusCmsPlugin\Entity\InfoArticleTranslationInterface
