sylius_resource:
    resources:
        bitbag_sylius_cms_plugin.map_point:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusCmsPlugin\Entity\MapPoint
                interface: BitBag\SyliusCmsPlugin\Entity\MapPointInterface
                form: BitBag\SyliusCmsPlugin\Form\Type\MapPointType
                repository: BitBag\SyliusCmsPlugin\Repository\MapPointRepository
            translation:
                classes:
                    model: BitBag\SyliusCmsPlugin\Entity\MapPointTranslation
                    interface: BitBag\SyliusCmsPlugin\Entity\MapPointTranslationInterface
