bitbag_sylius_cms_plugin_admin_info_article:
    resource: |
        alias: bitbag_sylius_cms_plugin.info_article
        section: admin
        templates: BitBagSyliusCmsPlugin:CrudUi
        redirect: update
        grid: bitbag_sylius_cms_plugin_admin_info_article
        except: ['show']
        permission: true
        vars:
            all:
                header: bitbag_sylius_cms_plugin.ui.info_articles_header
                subheader: bitbag_sylius_cms_plugin.ui.info_articles_subheader
                templates:
                    form: "@BitBagSyliusCmsPlugin/InfoArticle/Crud/_form.html.twig"
            index:
                icon: sticky note
    type: sylius.resource
