bitbag_sylius_cms_plugin_admin_map_point:
    resource: |
        alias: bitbag_sylius_cms_plugin.map_point
        section: admin
        templates: BitBagSyliusCmsPlugin:CrudUi
        redirect: update
        grid: bitbag_sylius_cms_plugin_admin_map_point
        except: ['show']
        permission: true
        vars:
            all:
                header: bitbag_sylius_cms_plugin.ui.map_points_header
                subheader: bitbag_sylius_cms_plugin.ui.map_points_subheader
                templates:
                    form: "@BitBagSyliusCmsPlugin/MapPoint/Crud/_form.html.twig"
            index:
                icon: sticky note
    type: sylius.resource
