BitBag\SyliusCmsPlugin\Entity\FrequentlyAskedQuestionSection:
  type: mappedSuperclass
  table: bitbag_cms_faq_section
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    code:
      column: code
      type: string
      length: 250
      unique: true
  oneToOne:
    image:
      targetEntity: BitBag\SyliusCmsPlugin\Entity\FrequentlyAskedQuestionSectionImage
      mappedBy: owner
      cascade: [ALL]
