BitBag\SyliusCmsPlugin\Entity\FrequentlyAskedQuestionSectionTranslation:
  type: mappedSuperclass
  table: bitbag_cms_faq_section_translation
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      column: name
      type: string
      nullable: true