BitBag\SyliusCmsPlugin\Entity\MapPoint:
    type: mappedSuperclass
    table: bitbag_cms_map_point
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            column: code
            type: string
            length: 250
            unique: true
        enabled:
            column: enabled
            type: boolean
        phoneNumber:
            column: phoneNumber
            type: string
            length: 250
        address:
            column: address
            type: string
            length: 250
        city:
            column: city
            type: string
            length: 250
        openingHours:
            column: openingHours
            type: string
            length: 250
        createdAt:
            column: created_at
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToMany:
        productVariants:
            targetEntity: Sylius\Component\Product\Model\ProductVariantInterface
            joinTable:
                name: bitbag_cms_map_point_product_variants
                joinColumns:
                    map_point_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    product_variant_id:
                        referencedColumnName: id
                        onDelete: CASCADE
        channels:
            targetEntity: Sylius\Component\Channel\Model\ChannelInterface
            joinTable:
                name: bitbag_cms_map_point_channels
                joinColumns:
                    map_point_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    channel_id:
                        referencedColumnName: id
                        onDelete: CASCADE
